<script src="/assets/compact-js/principal|index|index.js" type="text/javascript"></script>

<?php
/** @var $lista \Principal\Service\Principal[] */
?>

<div class="page-head">
    <br/><br/><br/><br/>
    <div class="container">
        <div align="center">
            <img src="/assets/img/logo/logo-menu2.png" max-width=" 150px" height="130px"/>
            <br/>
            <p style="font-size: 20px; color: #032a51">Sistema de análise das avaliações Enade</p>


        </div>
    </div>
    <?php //echo $this->Auth()->nm_usuario; ?>
    <?php //echo $this->Auth()->id_usuario; ?>
    <br/>

</div>

<br/><br/><br/>




<!---->
    <!--
        <ul class="topstats clearfix">
            <li class="col-xs-6 col-lg-3">
                <div class="kode-alert kode-alert-img alert3">
                    <img src="assets/img/icones/health3.png" class="img" alt="img">
                    <span class="diff">PACIENTES ATENDIDOS</span>

                    <h3 class="color4">18</h3>
                </div>
            </li>
            <li class="col-xs-6 col-lg-3">
                <div class="kode-alert kode-alert-img alert2">
                    <img src="assets/img/icones/patient2.png" class="img" alt="img">
                    <span class="diff">PACIENTES EM ESPERA</span>

                    <h3 class="color4">5</h3>
                </div>
            </li>
            <li class="col-xs-6 col-lg-3">
                <div class="kode-alert kode-alert-img alert1">
                    <img src="assets/img/icones/medical59.png" class="img" alt="img">
                    <span class="diff">MÉDICOS EM ATENDIMENTOS</span>

                    <h3 class="color4">3</h3>
                </div>
            </li>
            <li class="col-xs-6 col-lg-3">
                <div class="kode-alert kode-alert-img alert4">
                    <img src="assets/img/icones/nurse1.png" class="img" alt="img">
                    <span class="diff">TÉCNICOS DE SAÚDE</span>

                    <h3 class="color4">1</h3>
                </div>
            </li>

            <li class="col-xs-6 col-lg-3">
                <div class="kode-alert kode-alert-img alert5">
                    <img src="assets/img/icones/baby137.png" class="img" alt="img">
                    <span class="diff">RELATÓRIO DE NASCIMENTO</span>

                    <h3 class="color4">2</h3>
                </div>
            </li>
            <li class="col-xs-6 col-lg-3">
                <div class="kode-alert kode-alert-img alert6">
                    <img src="assets/img/icones/healthclinic2.png" class="img" alt="img">
                    <span class="diff">RELATÓRIO DE ÓBITO</span>

                    <h3 class="color4">1</h3>
                </div>
            </li>
            <li class="col-xs-6 col-lg-3">
                <div class="kode-alert kode-alert-img alert6">
                    <img src="assets/img/icones/person287.png" class="img" alt="img">
                    <span class="diff">RELATÓRIO DE CIRUGIA</span>

                    <h3 class="color4">2</h3>
                </div>
            </li>
            <li class="col-xs-6 col-lg-3">
                <div class="kode-alert kode-alert-img alert6">
                    <img src="assets/img/icones/medical99.png" class="img" alt="img">
                    <span class="diff">PEDIDOS DE TESTES</span>

                    <h3 class="color4">1</h3>
                </div>
            </li>
            <li class="col-xs-6 col-lg-3">
                <div class="kode-alert kode-alert-img alert6">
                    <img src="assets/img/icones/sick.png" class="img" alt="img">
                    <span class="diff">INTERNAÇÕES</span>

                    <h3 class="color4">4</h3>
                </div>
            </li>
            <li class="col-xs-6 col-lg-3">
                <div class="kode-alert kode-alert-img alert6">
                    <img src="assets/img/icones/patient3.png" class="img" alt="img">
                    <span class="diff">PACIENTES MEDICADOS</span>

                    <h3 class="color4">3</h3>
                </div>
            </li>
            <li class="col-xs-6 col-lg-3">
                <div class="kode-alert kode-alert-img alert6">
                    <img src="assets/img/icones/medical60.png" class="img" alt="img">
                    <span class="diff">PACIENTES EM TRATAMENTO</span>

                    <h3 class="color4">1</h3>
                </div>
            </li>
            <li class="col-xs-6 col-lg-3">
                <div class="kode-alert kode-alert-img alert6">
                    <img src="assets/img/icones/transfusion1.png" class="img" alt="img">
                    <span class="diff">BANCO DE SANGUE</span>

                    <h3 class="color4">120</h3>
                </div>
            </li>
            <li class="col-xs-6 col-lg-3">
                <div class="kode-alert kode-alert-img alert6">
                    <img src="assets/img/icones/medical96.png" class="img" alt="img">
                    <span class="diff">CONSULTAS MARCADAS</span>

                    <h3 class="color4">1</h3>
                </div>
            </li>
            <li class="col-xs-6 col-lg-3">
                <div class="kode-alert kode-alert-img alert6">
                    <img src="assets/img/icones/first21.png" class="img" alt="img">
                    <span class="diff">Pacientes Aguardando</span>

                    <h3 class="color4">2</h3>
                </div>
            </li>
            <li class="col-xs-6 col-lg-3">
                <div class="kode-alert kode-alert-img alert6">
                    <img src="assets/img/icones/hospital11.png" class="img" alt="img">
                    <span class="diff">CONSULTAS DESMARCADAS</span>

                    <h3 class="color4">0</h3>
                </div>
            </li>
            <li class="col-xs-6 col-lg-3">
                <div class="kode-alert kode-alert-img alert7">
                    <img src="assets/img/icones/skeleton.png" class="img" alt="img">
                    <span class="diff">PEDIDOS DE RAIO-X</span>

                    <h3 class="color4">1</h3>
                </div>
            </li>
            <li class="col-xs-6 col-lg-3">
                <div class="kode-alert kode-alert-img alert8">
                    <img src="assets/img/icones/electrocardiogram3.png" class="img" alt="img">
                    <span class="diff">PEDIDOS DE EXAMES</span>

                    <h3 class="color4">2</h3>
                </div>
            </li>
            <li class="col-xs-6 col-lg-3">
                <div class="kode-alert kode-alert-img alert9">
                    <img src="assets/img/icones/illness.png" class="img" alt="img">
                    <span class="diff">CAMAS/LEITOS DISPONÍVEIS</span>

                    <h3 class="color4">128</h3>
                </div>
            </li>
            <li class="col-xs-6 col-lg-3">
                <div class="kode-alert kode-alert-img alert10">
                    <img src="assets/img/icones/ambulance9.png" class="img" alt="img">
                    <span class="diff">Frota Ambulância</span>

                    <h3 class="color4">4</h3>
                </div>
            </li>
            <li class="col-xs-6 col-lg-3">
                <div class="kode-alert kode-alert-img alert11">
                    <img src="assets/img/icones/grana.png" class="img" alt="img">
                    <span class="diff">TOTAL DE CONSULTAS PAGAS</span>

                    <h3 class="color4">R$ 12.696,00</h3>
                </div>
            </li>
        </ul>

-->