<div class="row row-offcanvas row-offcanvas-right">
    <div class="col-xs-12 col-sm-9">
        <div class="well">
            <div class="page-head">
                <h2>Atualização de dados cadastrais</h2>
            </div>

            <dl>
                <dt>Alterar senha:</dt>
                <dd>
                    <a href="/usuario-usuario/alterar-senha/<?= Estrutura\Helpers\Cript::enc($form->get('id')->getValue())?>">Clique aqui para alterar a senha</a>
                </dd>
            </dl>

            <dl>
                <dt>E-mail atual:</dt>
                <dd><?= $form->get('em_email')->getValue(); ?></dd>
                <a href="/usuario-usuario/alterar-email/<?= Estrutura\Helpers\Cript::enc($form->get('id')->getValue())?>">Clique aqui para alterar o e-mail</a>
            </dl>

            <dl>
                <dt>Nome Completo:</dt>
                <dd><?= ucwords($usuario['nm_usuario'])
                    ?></dd>
            </dl>

            <?php
            $form->setAttribute('action', $this->url('navegacao', array('controller' => $controller, 'action' => 'gravar-atualizacao')));
            $form->setAttribute('method', 'post');
            $form->setAttribute('class', 'form-horizontal');
            $form->setAttribute('data-toggle', 'validator');
            $form->prepare();
            echo $this->form()->openTag($form);
            $form->get('id')->setValue(Estrutura\Helpers\Cript::enc($form->get('id')->getValue()));
            echo $this->formHidden($form->get('id'));
            ?>
            <?php
            if ($usuario['id_perfil'] != TXT_CONST_PERFIL_ADMINISTRADOR) {
                ?>
                <div class="form-group">
                    <div class="col-md-6">
                        <?= $this->formRow($form->get('nm_usuario')) ?>
                        <div class="help-block with-errors"></div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-6">
                        <?= $this->formRow($form->get('id_sexo')) ?>
                        <div class="help-block with-errors"></div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-6">
                        <?= $this->formRow($form->get('nm_funcao')) ?>
                        <div class="help-block with-errors"></div>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-6">
                        <?= $this->formRow($form->get('id_situacao_usuario')) ?>
                        <div class="help-block with-errors"></div>
                    </div>
                </div>

                <hr/>
                <div class="form-group">
                    <div class="col-md-6">
                        <button type="submit" class="btn btn-primary">Salvar</button>
                        <a href="<?= $this->url('navegacao', array('controller' => 'usuario-usuario', 'action' => 'index')) ?>"
                           class="btn btn-default">Voltar</a>
                    </div>
                </div>
            <?php
            }
            ?>

            <?= $this->form()->closeTag(); ?>
        </div>
        <?php

        ?>
    </div>


</div>
<script type="text/javascript"
        src="/assets/compact-js/validator.min.js,jquery.mask.min.js,usuario|usuario|atualizar-dados.js"></script>