<link href="/assets/css/usuario/usuario/cadastro.css" rel="stylesheet" />
<?php
if ($temPendenciaCadastral) {
    ?>
    <div class="bs-callout bs-callout-danger">
        Você tem pêndencias cadastrais. <a href="/usuario-usuario/atualizar-dados">Clique aqui para atualizar seus dados</a>
    </div>
    <?php
} else {

    if ($temSaqueComReciboEnviado) {
        ?>
        <div class="bs-callout bs-callout-info">
            Quando você envia um recibo de bônus, não é possível realizar atualizações cadastrais.
        </div>    
        <?php
    } else {
        ?>
        <div class="bs-callout bs-callout-info">
            <a href="/usuario-usuario/atualizar-dados">Clique aqui para atualizar seus dados</a>
        </div>    
        <?php
    }
}
?>
<br />
<h4>&nbsp;&nbsp;&nbsp;&nbsp;Dados Pessoais</h4>
<table class="table table-striped">
    <tbody>
        <tr>
            <td style="width: 30%"><h6><b class="pull-right">Nome Completo: </b></h6></td><td><h6><?= ucwords($usuario['nm_usuario']) ?></h6></td>
        </tr>
        <?php
        $dateAdesao = new \DateTime($usuario['dt_nascimento']);
        ?>
        <tr>
            <td><h6><b class="pull-right">Data de nascimento: </b></h6></td><td><h6><?= $dateAdesao->format('d/m/Y') ?></h6></td>
        </tr>
        <?php
        $trClass = $usuario['nm_nacionalidade'] ? '' : 'class="danger"';
        ?>
        <tr <?= $trClass ?>>
            <td><h6><b class="pull-right">Nascionalidade: </b></h6></td><td><h6><?= ucwords($usuario['nm_nacionalidade']) ?></h6></td>
        </tr>
        <?php
        $trClass = $usuario['nm_estado_civil'] ? '' : 'class="danger"';
        ?>
        <tr <?= $trClass ?>>
            <td><h6><b class="pull-right">Estado civil: </b></h6></td><td><h6><?= ucwords($usuario['nm_estado_civil']) ?></h6></td>
        </tr>
        <?php
        $trClass = $usuario['nm_profissao'] ? '' : 'class="danger"';
        ?>
        <tr <?= $trClass ?>>
            <td><h6><b class="pull-right">Profissão: </b></h6></td><td><h6><?= ucwords($usuario['nm_profissao']) ?></h6></td>
        </tr>
        <?php
        $trClass = $usuario['nu_cpf'] ? '' : 'class="danger"';
        ?>
        <tr <?= $trClass ?>>
            <td><h6><b class="pull-right">CPF: </b></h6></td><td><h6><?= \Estrutura\Helpers\Cpf::cpfMask($usuario['nu_cpf']) ?></h6></td>
        </tr>
        <?php
        $trClass = $usuario['nu_rg'] ? '' : 'class="danger"';
        ?>
        <tr <?= $trClass ?>>
            <td><h6><b class="pull-right">RG: </b></h6></td><td><h6><?= ucwords($usuario['nu_rg']) ?></h6></td>
        </tr>
        <tr>
            <td><h6><b class="pull-right">Telefone: </b></h6></td><td><h6><?= \Estrutura\Helpers\Telefone::telefoneMask($usuario['nr_ddd_telefone'] . $usuario['nr_telefone']) ?></h6></td>
        </tr>
        <?php
        $trClass = $usuario['nm_cidade'] ? '' : 'class="danger"';
        ?>
        <tr <?= $trClass ?>>
            <td><h6><b class="pull-right">Cidade: </b></h6></td><td><h6><?= ucwords($usuario['nm_cidade']) ?></h6></td>
        </tr>
        <?php
        $trClass = $usuario['nm_estado'] ? '' : 'class="danger"';
        ?>
        <tr <?= $trClass ?>>
            <td><h6><b class="pull-right">Estado: </b></h6></td><td><h6><?= ucwords($usuario['nm_estado']) ?></h6></td>
        </tr>
        <tr>
            <td><h6><b class="pull-right">E-mail: </b></h6></td><td><h6><?= $usuario['em_email'] ?></h6></td>
        </tr>
    </tbody>
</table> 
<h4>&nbsp;&nbsp;&nbsp;&nbsp;Endereço</h4>
<hr />
<table class="table table-striped">
    <tbody>
        <?php
        $trClass = $usuario['nm_logradouro'] ? '' : 'class="danger"';
        ?>
        <tr <?= $trClass ?>>
            <td style="width: 30%"><h6><b class="pull-right">Logradouro: </b></h6></td><td><h6><?= $usuario['nm_logradouro'] ?></h6></td>
        </tr>
        <?php
        $trClass = $usuario['nr_numero'] ? '' : 'class="danger"';
        ?>
        <tr <?= $trClass ?>>
            <td><h6><b class="pull-right">Número: </b></h6></td><td><h6><?= $usuario['nr_numero'] ?></h6></td>
        </tr>        
        <tr>
            <td><h6><b class="pull-right">Complemento: </b></h6></td><td><h6><?= $usuario['nm_complemento'] ?></h6></td>
        </tr>
        <?php
        $trClass = $usuario['nm_bairro'] ? '' : 'class="danger"';
        ?>
        <tr <?= $trClass ?>>
            <td><h6><b class="pull-right">Bairro: </b></h6></td><td><h6><?= $usuario['nm_bairro'] ?></h6></td>
        </tr>
        <?php
        $trClass = $usuario['nm_cidade'] ? '' : 'class="danger"';
        ?>
        <tr <?= $trClass ?>>
            <td><h6><b class="pull-right">Cidade: </b></h6></td><td><h6><?= $usuario['nm_cidade'] ?></h6></td>
        </tr>
        <?php
        $trClass = $usuario['nm_estado'] ? '' : 'class="danger"';
        ?>
        <tr <?= $trClass ?>>
            <td><h6><b class="pull-right">Estado: </b></h6></td><td><h6><?= $usuario['nm_estado'] ?></h6></td>
        </tr>
        <?php
        $trClass = $usuario['nr_cep'] ? '' : 'class="danger"';
        ?>
        <tr <?= $trClass ?>>
            <td><h6><b class="pull-right">CEP: </b></h6></td><td><h6><?= \Estrutura\Helpers\Cep::cepMask($usuario['nr_cep']) ?></h6></td>
        </tr>
    </tbody>
</table>
<h4>&nbsp;&nbsp;&nbsp;&nbsp;Dados Bancários</h4>
<hr />
<table class="table table-striped">
    <tbody>
        <?php
        $trClass = $usuario['nm_banco'] ? '' : 'class="danger"';
        ?>
        <tr <?= $trClass ?>>
            <td style="width: 30%"><h6><b class="pull-right">Banco: </b></h6></td><td><h6><?= $usuario['nm_banco'] ?></h6></td>
        </tr>
        <?php
        $trClass = $usuario['nr_agencia'] ? '' : 'class="danger"';
        ?>
        <tr <?= $trClass ?>>
            <td><h6><b class="pull-right">Agência: </b></h6></td><td><h6><?= $usuario['nr_agencia'] ?></h6></td>
        </tr>
        <?php
        $trClass = $usuario['nr_conta'] ? '' : 'class="danger"';
        ?>
        <tr <?= $trClass ?>>
            <td><h6><b class="pull-right">Nº conta: </b></h6></td><td><h6><?= $usuario['nr_conta'] ?></h6></td>
        </tr>
        <?php
        $trClass = $usuario['nm_tipo_conta'] ? '' : 'class="danger"';
        ?>
        <tr <?= $trClass ?>>
            <td><h6><b class="pull-right">Tipo de Conta: </b></h6></td><td><h6><?= $usuario['nm_tipo_conta'] ?></h6></td>
        </tr>        
    </tbody>
</table>