<link rel="stylesheet" href="/assets/compact-css/jquery.tablesorter.theme.bootstrap.css,jquery.tablesorter.pager.css">
<?php
/** @var $form \Usuario\Form\Usuario */
/** @var $lista \Usuario\Service\Usuario[] */
?>
<div class="page-head">
    <h2>Lista de Colaboradores</h2>
</div>
<div class="cl-mcont">
    <div class="row">
        <div class="col-md-12">
            <a class="btn btn-default" href="<?= $this->url('navegacao', array('controller' => $controller, 'action' => 'cadastro')) ?>" title="Adicionar Colaborador">Novo Colaborador</a>
        </div>
    </div>
    <br />
    <div class="row" id="usuario-pagination"></div>    
</div>

<script>
    $(function () {

        $.ajax({
            type: "post",
            dataType: "text",
            cache: false,
            url: '/usuario-usuario/index-pagination',
            async: true,
            data: {
            },
            beforeSend: function () {

                $('#usuario-pagination').html(
                        '<div class="row"><div class="col-md-12 text-center"><p><img src="/assets/img/carregando.gif"><p></div></div>'
                        );
            },
            success: function (data) {

                $('#usuario-pagination').html(data);
            }
        });

    })
</script>

