<div class="row_form">
    <div class="col-md-12 ">
        <div class="form-group">
            <div class="col-md-12">
                <?= $this->formRow($form->get('id_action')) ?>
                <div class="help-block with-errors"></div>
            </div>
        </div>
    </div>
</div>





<div class="form-group">
    <div class="col-md-10">
        <button type="submit" class="btn btn-primary">Salvar</button>
        <a href="<?= $this->url('navegacao', ['controller' => 'principal']) ?>" class="btn btn-default">Cancelar</a>
    </div>
</div>