<?php if ($this->Auth()) { ?>
    <ul class="nav navbar-nav">
        <li class="active"><a href="/principal">Início</a></li>
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Cadastros
                <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
                <li><a href="/turno">Turnos</a></li>
                <li><a href="/simulado">Simulado</a></li>
                <li><a href="/aluno">Aluno</a></li>
                <li><a href="/curso">Curso</a></li>
                <li><a href="/disciplina">Disciplina</a></li>
                <li><a href="/resultado">Resultado</a></li>
                <li><a href="/conteudo">Conteúdo</a></li>
                <li><a href="/conteudo_simulado">Conteúdo do Simulado</a></li>
            </ul>
        </li>
        <?php
        #Alysson - Exibe este item de menu apenas para administradores
        $usuario_logado = $this->Auth(); #Pega o Usuario Logado
        if (TXT_CONST_PERFIL_ADMINISTRADOR == $usuario_logado->id_perfil) { ?>
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    Configurações
                    <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                    <li><a href="/permissao/cadastro">Gerenciador de Permissões</a></li>
                    <li><a href="/controller">Cadastro Controller</a></li>
                    <li><a href="/action">Cadastro Action</a></li>
                </ul>
            </li>
        <?php } ?>

        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Básicos
                <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
                <li><a href="/usuario">Usuários</a></li>
                <li><a href="/perfil">Perfis</a></li>
            </ul>
        </li>

    </ul>

<?php } ?>
