<?php
#Constantes de Perfil
define('TXT_CONST_PERFIL_ADMINISTRADOR', 1);
define('TXT_CONST_PERFIL_PROFESSOR', 2);
define('TXT_CONST_VINCULO_RESPONSAVEL_ESCRITORIO', 1);
define('TXT_CONST_VINCULO_CONTATO', 2);

define('TXT_CONST_LOCAL_COMPLETO_UPLOAD', BASE_PATCH . DIRECTORY_SEPARATOR . 'data' . DIRECTORY_SEPARATOR . 'arquivos');
define('TXT_CONST_LOCAL_RELATIVO_UPLOAD', DIRECTORY_SEPARATOR . 'data' . DIRECTORY_SEPARATOR . 'arquivos' . DIRECTORY_SEPARATOR);