<?php
#Constantes de Perfil
define('TXT_CONST_PERFIL_ADMINISTRADOR_ADVE', 1);
define('TXT_CONST_PERFIL_ADMINISTRADOR', 2);
define('TXT_CONST_PERFIL_CLIENTE', 3);
define('TXT_CONST_VINCULO_RESPONSAVEL_ESCRITORIO', 1);
define('TXT_CONST_VINCULO_CONTATO', 2);