<link rel="stylesheet" type="text/css" href="/assets/css/bootstrap-datetimepicker.min.css" >  
<div class="cl-mcont">
    <?php
    $form->setAttribute('action', $this->url('navegacao', array('controller'=>$controller,'action' => 'gravar')));
    $form->setAttribute('method', 'post');
    $form->setAttribute('class', 'form-horizontal');
    $form->setAttribute('data-toggle', 'validator');
    $form->prepare();
    echo $this->form()->openTag($form);
    ?>
    <div class="row">
        <div class="col-md-6">
            <h4>Alterar dados do Aluno</h4>
        </div>
       </div>
    <div class="block-flat">
        <div class="content">

            <?php
            $form->get('id')->setValue(Estrutura\Helpers\Cript::enc($form->get('id')->getValue())); 
            echo $this->formHidden($form->get('id'));
            ?>
                <div class="form-group">
                        <div class="col-md-7">
                            <?=$this->formRow($form->get('id_curso'))?>
                            <div class="help-block with-errors"></div>
                        </div>
                    </div><div class="form-group">
                        <div class="col-md-7">
                            <?=$this->formRow($form->get('id_sexo'))?>
                            <div class="help-block with-errors"></div>
                        </div>
                    </div><div class="form-group">
                        <div class="col-md-7">
                            <?=$this->formRow($form->get('nm_aluno'))?>
                            <div class="help-block with-errors"></div>
                        </div>
                    </div><div class="form-group">
                        <div class="col-md-7">
                            <?=$this->formRow($form->get('nr_matricula'))?>
                            <div class="help-block with-errors"></div>
                        </div>
                    </div><div class="form-group">
                        <div class="col-md-7">
                            <?=$this->formRow($form->get('em_email'))?>
                            <div class="help-block with-errors"></div>
                        </div>
                    </div>
            <div class="row">
                <div class="col-md-12 text-right">
                    <button type="submit" class="btn btn-primary" title="Slavar">Salvar</button>
                    <a href="<?=$this->url('navegacao', ['controller'=>$controller])?>" class="btn btn-default" title="Voltar">Voltar</a>
                </div>
            </div>
        </div>
    </div>
    <?= $this->form()->closeTag(); ?>
</div>
<script src="/assets/compact-js/moment.js,bootstrap-datetimepicker.min.js,validator.min.js,jquery.mask.min.js,jquery.complexify.js,aluno|aluno|edita.js" type="text/javascript"></script>
