<footer>
    <div class="row">
        <div class="col-md-2">&nbsp;</div>
        <div class="col-md-8 text-center">
            <a href="/application-index/politica-privacidade">Política de Privacidade</a> | 
            <a href="/application-index/termo-utilizacao">Termos de Utilização do Serviço</a> | 
            <a href="/application-index/declaracao-seguranca">Declaração de Segurança</a>
            <br>
            <br>
            <a href="<?= $this->Config('dominio') ?>" title="<?= $this->Config('nome_projeto') ?> - <?= $this->Config('slogan') ?>">
                <img src="/assets/img/logo/logo-menu.png" />
            </a>
            <br>
            <br>
            <!-- Abre as politicas em forma de Modal.-->
<!--            <a href="#" data-toggle="modal" data-target="#myModalPoliticas">Política de Privacidade</a> | <a href="#" data-toggle="modal" data-target="#myModalTermos">Termos de Utilização</a> | <a href="#" data-toggle="modal" data-target="#myModalDeclaracao">Declaração de Segurança</a>-->

            <p>Copyright©<?= date('Y'); ?> <?= $this->Config('nome_projeto') ?> - <?= $this->Config('slogan') ?></p>
            <p><?= $this->ConfigService('email_admin') ?> | +55<?= \Estrutura\Helpers\Telefone::telefoneMask($this->ConfigService('telefone_admin')) ?> | <?= \Estrutura\Helpers\Url::urlFilter($this->Config('dominio')) ?></p>
        </div>
        <div class="col-md-2">&nbsp;</div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <?php $obVersionamento = new \Estrutura\View\Helper\Versionamento(); ?>
            <div class="versao" style="text-align: center;"><?php echo $obVersionamento->getGitFullVersion() ; ?></div>
        </div>
    </div>
    <br>    
</footer>


<!-- Modal -->
<div class="modal fade" id="myModalPoliticas" tabindex="-1" role="dialog" aria-labelledby="myModalPoliticasLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalPoliticasLabel">Política de Privacidade</h4>
            </div>
            <div class="modal-body">

                <h3> Política de Privacidade </h3>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
            </div>
        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="myModalTermos" tabindex="-1" role="dialog" aria-labelledby="myModalTermosLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalTermosLabel">Termos de Utilização</h4>
            </div>
            <div class="modal-body">

                <h3> Termos de Utilização </h3>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
            </div>
        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="myModalDeclaracao" tabindex="-1" role="dialog" aria-labelledby="myModalDeclaracaoLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalDeclaracaoLabel">Declaraçao de Segurança</h4>
            </div>
            <div class="modal-body">

                <h3> Declaraçao de Segurança</h3>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
            </div>
        </div>
    </div>
</div>
