<link rel="stylesheet" type="text/css" href="/assets/css/selectize.bootstrap2.css"/>
<br/>
<div class="row row-offcanvas row-offcanvas-center">
    <div class="col-xs-12 col-sm-12">
        <div class="panel panel-info">
            <div class="panel-heading">
                <h3 class="light panel-title">Criar uma conta no ADV-e</h3>
            </div>
            <div class="panel-body" style="background-color: white;">
                <?php
                $form->setAttribute('action', $this->url('navegacao', array('controller' => 'auth', 'action' => 'gravar-escritorio')));
                $form->setAttribute('method', 'post');
                $form->setAttribute('class', 'form-horizontal');
                $form->setAttribute('data-toggle', 'validator');
                $form->prepare();
                echo $this->form()->openTag($form);
                $form->get('id')->setValue(Estrutura\Helpers\Cript::enc($form->get('id')->getValue()));
                echo $this->formHidden($form->get('id'));
                ?>
                <div class="form-group">
                    <div class="col-md-6">
                        <?= $this->formRow($form->get('nm_pessoa_fisica')) ?>
                        <div class="help-block with-errors"></div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-6">
                        <?= $this->formRow($form->get('nm_sobrenome')) ?>
                        <div class="help-block with-errors"></div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-6">
                        <?= $this->formRow($form->get('em_email')) ?>
                        <div class="help-block with-errors"></div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-6">
                        <?= $this->formRow($form->get('em_email_confirm')) ?>
                        <div class="help-block with-errors"></div>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-6">
                        <?= $this->formRow($form->get('pw_senha')) ?>
                        <div class="help-block with-errors"></div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-6">
                        <?= $this->formRow($form->get('pw_senha_confirm')) ?>
                        <div class="help-block with-errors"></div>
                    </div>
                </div>
            </div>
        </div>
        <!--  Fim do Painel-->
        <div class="form-group">
            <div class="col-md-12">
                <button type="submit" class="btn btn-primary">Criar Conta</button>
                <a href="<?= $this->url('navegacao', ['controller' => 'auth', 'action' => 'login']) ?>"
                   class="btn btn-default">Voltar</a>
            </div>
        </div>
        <?php
        echo $this->form()->closeTag();
        ?>
    </div>
</div>
<script src="/assets/compact-js/validator.min.js,jquery.mask.min.js" type="text/javascript"></script>
<script>
    $(function () {
        $("footer").remove();
    });
</script>