<link rel="stylesheet" type="text/css" href="/assets/css/selectize.bootstrap2.css"/>
<div class="row row-offcanvas row-offcanvas-right">
    <div class="center-block col-md-5" style="float: none; padding-top: 8%;">
        <div class="col-xs-10 col-sm-10">
            <div class="panel panel-info">
                <div class="panel-heading">
                    <h3 class="light panel-title">Login</h3>
                </div>
                <div class="panel-body">
                    <?php
                    $form = $this->form;
                    $form->setAttribute('action', $this->url('authenticate'));
                    $form->setAttribute('method', 'post');
                    $form->setAttribute('class', 'form-horizontal');

                    $form->prepare();
                    echo $this->form()->openTag($form);
                    ?>

                    <div class="form-group">
                        <div class="col-md-12">
                            <?= $this->formRow($form->get('email')) ?>
                            <div class="help-block with-errors"></div>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-12">
                            <?= $this->formRow($form->get('senha')) ?>
                            <div class="help-block with-errors"></div>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-12">
                            <button type="submit" class="btn btn-primary">Acessar</button>
                        </div>
                    </div>
                    <br>

                    <div class="form-group text-center">
                        <div class="col-md-12">
                            <a href="/auth/esqueci-senha" class="pull-left">Esqueci a Senha</a>
                            &nbsp;|&nbsp;
                            <a href="/auth/cadastro-escritorio" class="pull-right">Criar Conta</a>
                        </div>
                    </div>
                    <?php
                    echo $this->form()->closeTag();
                    ?>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    $(function () {
        $("footer").remove();
    });
</script>