<script src="/assets/compact-js/application|index|index.js" type="text/javascript"></script>
<div class="row row-offcanvas row-offcanvas-right">

    <div class="col-xs-12 col-sm-9">

        <div class="jumbotron">
            <h2>Política de Privacidade</h2>
            <p class="text-justify">
                <span>A ADV-e Advocacia Inteligente On-line está empenhada em proteger a privacidade das  informações pessoais dos usuários de seus produtos e serviços. Esta Política de Privacidade descreve as práticas de privacidade de informação aplicáveis ao sistema ADV-e Advocacia Inteligente On-line ("ADV-e" ou "sistema") informando como são feitas a coleta, o uso e a divulgação das informações dentro do sistema.</span>
            </p>
        </div>
        <div class="row">
            <div class="col-6 col-sm-6 col-lg-6">                
                <h3>
                    <span>Link para sites de terceiros</span>
                </h3>
                <p class="text-justify">
                    <span>O ADV-e pode conter links para sites de terceiros. A ADV-e Advocacia Inteligente On-line não possui controle nem é responsável pelas práticas de privacidade de informação ou pelo conteúdo desses sites. Assim, encorajamos você a consultar as políticas de privacidade destes outros sites de forma a compreender as suas respectivas práticas de privacidade de informação.</span>
                </p>
                <h3>
                    <span>Informações Pessoais Coletadas</span>
                </h3>
                <p class="text-justify">
                    <span>O ADV-e pode coletar informações de diferentes formas:</span>
                </p>
                <p class="text-justify">
                    <span>- Informações sobre usuários cadastradas pelos administradores do sistema: Nome, Telefone, e-mail, etc.</span>
                </p>
                <p class="text-justify">
                    <span>
                        A ADV-e Advocacia Inteligente On-line se compromete a utilizar toda e qualquer informação sobre usuário coletada, incluindo seus dados pessoais, dentro dos limites legais.<br><br>
                        AA ADV-e Advocacia Inteligente On-line não comercializará informações dos usuários.
                    </span>
                </p>
                <h3>
                    <span>Proteção das Informações</span>
                </h3>
                <p class="text-justify">
                    <span>As informações das contas dos usuários são protegidas por senhas para sua privacidade e segurança das mesmas.</span>
                </p>               
                <p class="text-justify">
                    <span>O ADV-e protege as informações prestadas em formulários web através da tecnologia Secure Socket Layer ("SSL") que resguarda os dados do usuário usando autenticação do servidor e encriptação de dados.</span>
                </p>
                <p class="text-justify">
                    <span>O ADV-e utiliza criptografia das informações armazenadas no banco de dados.</span>
                </p>
                <p class="text-justify">
                    <span>O ADV-e possui um registro de Log das atividades executadas.</span>
                </p>
            </div>
            <div class="col-6 col-sm-6 col-lg-6">
                <h3>
                    <span>Utilização das Informações Recolhidas</span>
                </h3>
                <p class="text-justify">
                    <span>O ADV-e coleta informações apenas com o objetivo de executar as funções do sistema: identificar e autenticar usuários e executar processos operacionais.</span>
                </p>
                <p class="text-justify">
                    <span>A permissão de acesso às informações é definida exclusivamente pelo administrador do sistema, por meio de configuração da política de controle de acesso dentro do sistema.</span>
                </p>            
                <h3>
                    <span>Alterações na Política de Privacidade</span>
                </h3>
                <p class="text-justify">
                    <span>Esta Política poderá ser revisada de tempos em tempos. A "última atualização" foi realizada no dia primeiro de setembro de 2016.</span>
                </p>
                <h3>
                    <span>Como contactar-nos</span>
                </h3>
                <p class="text-justify">
                    <span>Quaisquer questões relativas a esta Política de Privacidade ou a outras práticas de privacidade do ADV-e deverão ser dirigidas à ADV-e Advocacia Inteligente On-line enviando um e-mail para o <a href="mailto:admin@acthosti.com.br">contato@acthosti.com.br</a>.</span>
                </p>
            </div>
        </div>
    </div><!--/span-->
</div><!--/row-->




